name: Compile and commit PDFs next to .tex files

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: self-hosted

    permissions:
      contents: write  # serve per poter fare commit e push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: mostra PDF trovati
        run: find . -name '*.pdf'

      - name: Get changed .tex files
        id: changed
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.tex$' || true)
          echo "changed_files=$CHANGED" >> $GITHUB_ENV
          echo "File modificati: $CHANGED"

      # - name: Get changed .tex files
      #   id: changed
      #   run: |
      #     git fetch origin ${{ github.ref_name }} --depth=2 || true
      #     CHANGED=$(git diff --name-only HEAD~1 HEAD | grep '\.tex$' || true)
      #     echo "changed_files=$CHANGED" >> $GITHUB_ENV
      #     echo "File modificati: $CHANGED"

      - name: Compile changed .tex files to PDFs
        if: env.changed_files != ''
        run: |
          for f in $changed_files; do
            echo "Compilando $f..."
            dir=$(dirname "$f")
            base=$(basename "$f" .tex)
            latexmk -pdf -interaction=nonstopmode -halt-on-error -output-directory="$dir" "$f" || echo "Errore nella compilazione di $f"
            echo "Creato $dir/$base.pdf"
          done

      - name: Commit and push generated PDFs
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          FILES="${changed_files:-$CHANGED}"

          declare -a to_add=()
          while IFS= read -r f; do
            [ -z "$f" ] && continue
            dir=$(dirname "$f")
            base=$(basename "$f" .tex)
            pdf="$dir/$base.pdf"
            if [ -f "$pdf" ]; then
              to_add+=("$pdf")
            fi
          done <<< "$FILES"

          if [ ${#to_add[@]} -eq 0 ]; then
            echo "❌ Nessun PDF trovato da aggiungere."
            exit 0
          fi

          echo "✅ Aggiungo i seguenti PDF:"
          printf '%s\n' "${to_add[@]}"

          git add -- "${to_add[@]}"
          git commit -m "Auto-compile LaTeX → PDF" || echo "Nessun PDF nuovo da committare"
          git push origin HEAD:${{ github.ref_name }}
