name: Compile and commit PDFs next to .tex files

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # serve per poter fare commit e push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed .tex files
        id: changed
        run: |
          git fetch origin ${{ github.ref_name }} --depth=2 || true
          CHANGED=$(git diff --name-only HEAD~1 HEAD | grep '\.tex$' || true)
          echo "changed_files=$CHANGED" >> $GITHUB_ENV
          echo "File modificati: $CHANGED"

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk texlive-full

      - name: Compile changed .tex files to PDFs
        if: env.changed_files != ''
        run: |
          for f in $changed_files; do
            echo "Compilando $f..."
            dir=$(dirname "$f")
            base=$(basename "$f" .tex)
            latexmk -pdf -interaction=nonstopmode -halt-on-error -output-directory="$dir" "$f" || echo "Errore nella compilazione di $f"
            echo "Creato $dir/$base.pdf"
          done

      - name: Commit and push generated PDFs
        if: env.changed_files != ''
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add '**/*.pdf'
          git commit -m "Auto-compile LaTeX → PDF [skip ci]" || echo "Nessun PDF nuovo da committare"
          git push origin HEAD:${{ github.ref_name }}
